### ISSUE TITLE
Transfer to WebTorrent organization

### ISSUE THREAD

**Issue by feross** [webtorrent/ut_pex#10]
Hey @fisch0920, I moved all my personal WebTorrent repos into a new [WebTorrent organization](https://github.com/webtorrent).

If it's okay with you, can you transfer this repo to the "webtorrent" organization? 🙏

**Comment by fisch0920** [comment]
In progress :)

**Comment by feross** [comment]
Awesome!

Feross
Blog <http://feross.org/> | WebTorrent <https://webtorrent.io/> | Study
Notes <https://www.apstudynotes.org/>

**Comment by feross** [comment]
This is done now! https://github.com/webtorrent/ut_pex
