### ISSUE TITLE
Release a new version with latest changes

### ISSUE THREAD

**Issue by rogerg93** [webtorrent/ut_pex#28]
**What version of this package are you using?**
v2.0.0

**What problem do you want to solve?**
Update version of the package, so that changes made in [here](https://github.com/webtorrent/ut_pex/pull/26) are released and can be used in webtorrent package

**What do you think is the correct solution to this problem?**
Release a new version of the package

**Are you willing to submit a pull request to implement this change?**
Pull request is not needed

**Comment by feross** [comment]
Published 2.0.1

**Comment by rogerg93** [comment]
Thank you!
