### ISSUE TITLE
Camelcase the properties in the flags object?

### ISSUE THREAD

**Issue by feross** [webtorrent/ut_pex#29]
Pulling my comment into it's own issue:

The only last bit of feedback I have is that it might be nice to camelCase the properties in the flags object. Let me know your thoughts on that, and then we can do a major version release of `ut_pex` and get these improvements into `webtorrent`. @hicom150

_Originally posted by @feross in https://github.com/webtorrent/ut_pex/pull/27#issuecomment-717585496_

**Comment by hicom150** [comment]
Yeah that's a good point 👍
I've added #30 with the change 😉

**Comment by feross** [comment]
Fixed by #30

**Comment by feross** [comment]
Released as 3.0.0!
